version: '2'
services:
  db:
    build:
      context: db/
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root #rootパスワードの設定
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./db/mysql_data:/db/mysql_data
    ports:
      - "3306:3306"
  app:
    build:
      context: app/
    volumes:
      - ./app/:/go/src/app
    command: realize start --run --no-config # DEBUG
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db